[theme]
base = "dark"
primaryColor = "forestGreen"
backgroundColor = "#C8EAF2"
secondaryBackgroundColor = "#1A1D23"
textColor = "black"
font = "sans serif"


[theme.sidebar]
backgroundColor="#007EB5"
textColor="white"