# Generated by Django 5.2.7 on 2026-01-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='N/A')),
                ('genre', models.CharField(default='N/A', max_length=100)),
                ('categorie_createur', models.TextField(default='N/A')),
                ('origin', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type_etiquette', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='N/A', max_length=100)),
                ('status_producteur', models.CharField(default='N/A', max_length=100)),
                ('type_producteur', models.CharField(default='N/A', max_length=100)),
                ('model_eco', models.CharField(default='N/A', max_length=100)),
                ('natif_enrichi', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(default='N/A')),
                ('collection', models.TextField(default='N/A')),
                ('resume_officiel', models.TextField(default='N/A')),
                ('nom_host', models.TextField(default='N/A')),
                ('date_premier_episode', models.DateField(blank=True, null=True)),
                ('date_derniere_episode', models.DateField(blank=True, null=True)),
                ('datediff', models.IntegerField(default=0)),
                ('periodicite', models.TextField(default='N/A')),
                ('interrompu_moment_1_collection', models.TextField(default='N/A')),
                ('interrompu_moment_2_collection', models.TextField(default='N/A')),
                ('nb_episode_collecte_1', models.IntegerField(default=0)),
                ('nb_episode_collecte_2', models.IntegerField(default=0)),
                ('nb_episode_collecte_1_media', models.IntegerField(default=0)),
                ('nb_episode_collecte_2_media', models.IntegerField(default=0)),
                ('duree_moyenne', models.FloatField(default=0)),
                ('duree_variable', models.TextField(default='N/A')),
                ('audience_site_nb_ecoute', models.IntegerField(default=0)),
                ('audience_apple_classement', models.IntegerField(default=0)),
                ('audience_apple_note', models.FloatField(default=0)),
                ('audience_castbox_abonnement', models.IntegerField(default=0)),
                ('audience_castbox_nb_ecoute', models.IntegerField(default=0)),
                ('audience_podcastaddict_abonnement', models.IntegerField(default=0)),
                ('audience_youtube_nb_vue', models.IntegerField(default=0)),
                ('audience_soundcloud_nb_ecoute', models.IntegerField(default=0)),
                ('nb_telechargement_france', models.IntegerField(default=0)),
                ('nb_telechargement_monde', models.IntegerField(default=0)),
                ('date_collecte_1', models.DateField(blank=True, null=True)),
                ('date_collecte_2', models.DateField(blank=True, null=True)),
                ('createur', models.ManyToManyField(related_name='podcasts', to='main.createur')),
                ('etiquette', models.ManyToManyField(related_name='podcasts', to='main.etiquette')),
                ('genre', models.ManyToManyField(related_name='podcasts', to='main.genre')),
                ('motcle', models.ManyToManyField(related_name='podcasts', to='main.motcle')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(blank=True, max_length=50, null=True)),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plateforme')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.podcast')),
            ],
            options={
                'db_table': 'main_podcast_plateforme',
                'unique_together': {('podcast', 'plateforme')},
            },
        ),
        migrations.AddField(
            model_name='podcast',
            name='plateforme',
            field=models.ManyToManyField(related_name='podcasts', through='main.PodcastPlateforme', to='main.plateforme'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='producteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts', to='main.producteur'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='recompense',
            field=models.ManyToManyField(related_name='podcasts', to='main.recompense'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='rubrique',
            field=models.ManyToManyField(related_name='podcasts', to='main.rubrique'),
        ),
    ]
