# Generated by Django 5.2 on 2025-08-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Createur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='N/A', max_length=100)),
                ('prenom', models.CharField(default='N/A', max_length=100)),
                ('mail', models.CharField(default='N/A', max_length=100)),
                ('genre', models.CharField(default='N/A', max_length=100)),
                ('is_host', models.CharField(default='N/A', max_length=100)),
                ('categoeir_createur', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type_etiquette', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='N/A', max_length=100)),
                ('model_eco', models.CharField(default='N/A', max_length=100)),
                ('natif_enrichi', models.CharField(default='N/A', max_length=100)),
                ('nb_episode_collecte_1', models.SmallIntegerField(default=0)),
                ('nb_episode_collecte_2', models.SmallIntegerField(default=0)),
                ('status_producteur', models.CharField(default='N/A', max_length=100)),
                ('type_producteur', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recompense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='N/A', max_length=100)),
                ('date_premier_episode', models.DateField()),
                ('date_derniere_episode', models.DateField()),
                ('datediff', models.SmallIntegerField(default=0)),
                ('periodicite', models.CharField(default='N/A', max_length=100)),
                ('interrompu_moment_1_collection', models.CharField(default='N/A', max_length=100)),
                ('interrompu_moment_2_collection', models.CharField(default='N/A', max_length=100)),
                ('nb_episode_collecte_1', models.SmallIntegerField(default=0)),
                ('nb_episode_collecte_2', models.SmallIntegerField(default=0)),
                ('duree_moyenne', models.SmallIntegerField(default=0)),
                ('duree_variable', models.CharField(default='N/A', max_length=100)),
                ('date_collecte_1', models.DateField()),
                ('date_collecte_2', models.DateField()),
                ('nb_telechargement_france', models.IntegerField(default=0)),
                ('nb_telechargement_monde', models.IntegerField(default=0)),
                ('collection', models.ManyToManyField(blank=True, related_name='podcast', to='main.collection')),
                ('createur', models.ManyToManyField(blank=True, related_name='podcast', to='main.createur')),
                ('etiquette', models.ManyToManyField(blank=True, related_name='podcast', to='main.etiquette')),
                ('genre', models.ManyToManyField(blank=True, related_name='podcast', to='main.genre')),
                ('motcle', models.ManyToManyField(blank=True, related_name='podcast', to='main.motcle')),
                ('plateforme', models.ManyToManyField(blank=True, related_name='podcast', to='main.plateforme')),
                ('producteur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='main.producteur')),
                ('recompense', models.ManyToManyField(blank=True, related_name='podcast', to='main.recompense')),
                ('rubrique', models.ManyToManyField(blank=True, related_name='podcast', to='main.rubrique')),
            ],
        ),
    ]
